@startuml Web論文システムクラス図
skinparam classAttributeIconSize 0
hide circle

class 学生 {
 -学生ID
 -名前
 -生年月日
 -電話番号
 -入学年月日
 -卒業年月日

 +入学する()
 +専門分野を決める()
 +卒業する()
}

class 専門分野 {
 -分野ID
 -分野名

 +分野を追加()
 +分野を削除()
}

class 論文 {
 -論文ID
 -タイトル
 -審査結果
 -提出日
 -承認日

 +論文を登録する()
 +論文を審査する()
}

学生 o-- 専門分野
論文 o-- 学生
論文 o-- 専門分野

@enduml