@startuml Web論文システムドメインモデル図
skinparam componentStyle rectangle

' 学生
' 名前、生年月日、専門分野、入学年月日、卒業年月日
[学生] o-- [名前]
[学生] o-- [生年月日]
[学生] o-- [電話番号]
[学生] o-- [専門分野]
[学生] o-- [入学年月日]
[学生] o-- [卒業年月日]

' 専門分野
' 分野名、登録年月日
[専門分野] o-- [分野名]
[専門分野] o-- [登録年月日]

' 論文
' タイトル、審査結果、提出日、承認日
[論文] o-- [学生]
[論文] o-- [専門分野]
[論文] o-- [タイトル]
[論文] o-- [審査結果]
[論文] o-- [提出日]
[論文] o-- [承認日]

@enduml